name: Vulkan Display Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CPPFLAGS: "-I${GITHUB_WORKSPACE}/linux"

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get install autoconf automake autoconf-archive libvulkan-dev libx11-dev libxext-dev glslang-tools

    - name: Generate Autoconf Scripts
      run: ./autogen.sh
      working-directory: display

    - name: Configure
      run: ./configure
      working-directory: display

    - name: Build
      run: make
      working-directory: display

    - name: Run Tests
      run: make check
      working-directory: display

    - name: Run Release Tests
      run: make distcheck
      working-directory: display
